cabal-version: 3.14
name: knowledge-objects
version: 0.1.0.0
synopsis: Specification of ToEE objects
license: GPL-3.0-or-later
license-file: LICENSE
author: Dan Doel
maintainer: dan.doel@gmail.com
copyright: 2025
category: Game
build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options:
    -Wall -Wno-name-shadowing

library
  import: warnings

  exposed-modules:
    Temple.Object.Field
    Temple.Object.Field.General
    Temple.Object.Field.Portal
    Temple.Object.Field.Container
    Temple.Object.Field.Scenery
    Temple.Object.Field.Projectile
    Temple.Object.Field.Item
    Temple.Object.Field.Weapon
    Temple.Object.Field.Ammo
    Temple.Object.Field.Armor
    Temple.Object.Field.Money
    Temple.Object.Field.Food
    Temple.Object.Field.Scroll
    Temple.Object.Field.Key
    Temple.Object.Field.Written
    Temple.Object.Field.Bag
    Temple.Object.Field.Generic
    Temple.Object.Field.Critter
    Temple.Object.Field.Pc
    Temple.Object.Field.Npc
    Temple.Object.Field.Trap
    Temple.Object.Field.Extra

    Temple.Object.Field.Type

    Temple.Object.Script
    Temple.Object.Skill
    Temple.Object.Type

  build-depends:
    base ^>=4.20.1.0,
    megaparsec ^>=9.7.0

  hs-source-dirs: src
  default-language: GHC2024

  default-extensions:
    OverloadedStrings
    ViewPatterns
